from __future__ import annotations

import argparse
import csv
import subprocess
import sys
from datetime import datetime
from pathlib import Path


def normalize_csv_rows(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    normalized_rows: list[dict[str, str]] = []
    for row in rows:
        normalized_rows.append(
            {
                (key.lstrip("\ufeff").strip() if key else key): value
                for key, value in row.items()
            }
        )
    return normalized_rows


def positive_int(value: str) -> int:
    parsed = int(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("Value must be a positive integer.")
    return parsed


def non_negative_int(value: str) -> int:
    parsed = int(value)
    if parsed < 0:
        raise argparse.ArgumentTypeError("Value must be zero or a positive integer.")
    return parsed


def hour_of_day(value: str) -> int:
    parsed = int(value)
    if parsed < 0 or parsed > 23:
        raise argparse.ArgumentTypeError("Hour must be between 0 and 23.")
    return parsed


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run the cadence-specific free Reddit collection manifests that are due "
            "for the current hour, using public .json endpoints."
        )
    )
    parser.add_argument(
        "--schedule-plan",
        default="configs/schedules/schedule_plan.csv",
        help="Schedule plan CSV generated by build_schedule_manifests.py.",
    )
    parser.add_argument(
        "--output-dir",
        default="data/raw/reddit_json",
        help="Directory where mixed raw JSON files will be saved.",
    )
    parser.add_argument(
        "--timeout-seconds",
        type=positive_int,
        default=1800,
        help="Timeout in seconds for each free discovery schedule call.",
    )
    parser.add_argument(
        "--hour",
        type=hour_of_day,
        help="Override the current local hour for testing.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print which free schedules would run for the chosen hour.",
    )
    parser.add_argument(
        "--retries",
        type=non_negative_int,
        default=1,
        help="How many extra retry attempts to make after a failed schedule call.",
    )
    parser.add_argument(
        "--stop-on-error",
        dest="continue_on_error",
        action="store_false",
        help="Stop immediately when a schedule fails instead of continuing.",
    )
    parser.set_defaults(continue_on_error=True)
    return parser.parse_args()


def load_schedule_plan(path: Path) -> list[dict[str, str]]:
    if not path.is_file():
        raise SystemExit(f"Schedule plan not found: {path}")
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        rows = normalize_csv_rows(list(reader))
    if not rows:
        raise SystemExit("Schedule plan is empty.")
    required = {"schedule_name", "run_hours", "manifest_path", "cadence_label"}
    if not required.issubset(rows[0].keys()):
        joined = ", ".join(sorted(required))
        raise SystemExit(f"Schedule plan must contain: {joined}")
    return rows


def load_manifest(path: Path) -> list[dict[str, str]]:
    if not path.is_file():
        raise SystemExit(f"Manifest not found: {path}")
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        rows = normalize_csv_rows(list(reader))
    if not rows:
        raise SystemExit(f"Manifest is empty: {path}")
    required = {"subreddit", "listing", "top_time", "max_post_count", "max_comments"}
    if not required.issubset(rows[0].keys()):
        joined = ", ".join(sorted(required))
        raise SystemExit(f"Manifest must contain: {joined}")
    return rows


def hour_matches(run_hours: str, hour: int) -> bool:
    value = run_hours.strip()
    if value == "*":
        return True
    allowed = {
        int(part.strip())
        for part in value.split(",")
        if part.strip()
    }
    return hour in allowed


def resolve_due_rows(rows: list[dict[str, str]], hour: int) -> list[dict[str, str]]:
    return [row for row in rows if hour_matches(row.get("run_hours", ""), hour)]


def coerce_shared_value(rows: list[dict[str, str]], key: str, default: str = "") -> str:
    values = {(row.get(key) or "").strip() for row in rows}
    values.discard("")
    if not values:
        return default
    if len(values) > 1:
        joined = ", ".join(sorted(values))
        raise SystemExit(f"Manifest has mixed {key} values: {joined}")
    return next(iter(values))


def build_command(
    *,
    collector_script: Path,
    output_dir: str,
    schedule_name: str,
    cadence_label: str,
    scheduled_hour: int,
    manifest_rows: list[dict[str, str]],
) -> list[str]:
    subreddits = [(row.get("subreddit") or "").strip() for row in manifest_rows if (row.get("subreddit") or "").strip()]
    listing = coerce_shared_value(manifest_rows, "listing", default="new")
    top_time = coerce_shared_value(manifest_rows, "top_time")
    max_post_count = coerce_shared_value(manifest_rows, "max_post_count", default="100")
    max_comments = coerce_shared_value(manifest_rows, "max_comments", default="0")

    command = [
        sys.executable,
        str(collector_script),
        *subreddits,
        "--post-limit",
        max_post_count,
        "--comment-limit-per-post",
        max_comments,
        "--sort",
        listing,
        "--output-format",
        "reddit_json",
        "--output-dir",
        output_dir,
        "--schedule-name",
        schedule_name,
        "--cadence-label",
        cadence_label,
        "--scheduled-hour",
        f"{scheduled_hour:02d}",
    ]
    if listing == "top" and top_time:
        command.extend(["--time-filter", top_time])
    return command


def run_command(command: list[str], timeout_seconds: int) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        capture_output=True,
        text=True,
        timeout=timeout_seconds,
        check=False,
    )


def main() -> None:
    args = parse_args()
    target_hour = args.hour if args.hour is not None else datetime.now().hour
    plan_rows = load_schedule_plan(Path(args.schedule_plan))
    due_rows = resolve_due_rows(plan_rows, target_hour)

    if not due_rows:
        print(f"No free discovery schedules are due at hour {target_hour:02d}.")
        return

    collector_script = Path(__file__).with_name("collect_reddit_free.py")
    if not collector_script.is_file():
        raise SystemExit(f"Collector script not found: {collector_script}")

    print(f"Hour {target_hour:02d}: due free discovery schedules:")
    for row in due_rows:
        print(
            f"- {row['schedule_name']}: {row['manifest_path']} "
            f"({row.get('description', '')})"
        )

    if args.dry_run:
        return

    total_failures = 0
    for schedule_index, schedule_row in enumerate(due_rows, start=1):
        manifest_path = Path(schedule_row["manifest_path"])
        manifest_rows = load_manifest(manifest_path)
        command = build_command(
            collector_script=collector_script,
            output_dir=args.output_dir,
            schedule_name=schedule_row["schedule_name"],
            cadence_label=schedule_row.get("cadence_label", ""),
            scheduled_hour=target_hour,
            manifest_rows=manifest_rows,
        )
        print(
            f"Running free schedule {schedule_index}/{len(due_rows)}: "
            f"{schedule_row['schedule_name']}"
        )

        completed: subprocess.CompletedProcess[str] | None = None
        for attempt in range(args.retries + 1):
            completed = run_command(command, args.timeout_seconds)
            if completed.returncode == 0:
                break
            if attempt < args.retries:
                print(
                    f"  Attempt {attempt + 1} failed for {schedule_row['schedule_name']}; retrying..."
                )
        assert completed is not None

        if completed.stdout.strip():
            print(completed.stdout.strip())
        if completed.stderr.strip():
            print(completed.stderr.strip())

        if completed.returncode != 0:
            total_failures += 1
            if not args.continue_on_error:
                raise SystemExit(
                    f"Free schedule {schedule_row['schedule_name']} failed with exit code "
                    f"{completed.returncode}."
                )

    if total_failures:
        raise SystemExit(
            f"Free discovery completed with {total_failures} failed schedule(s)."
        )


if __name__ == "__main__":
    main()
